### PR TITLE
Actualizar vision guide app (prototipo)

### PR DESCRIPTION
**Pull request by ghost**
Prototype to develop an app that facilitates the daily life of blind people.

### CODE REVIEW

**Comment by Sammxes** [comment]
@Sourcery-ai review

**Review by ghost — COMMENTED** [review]
Need to edit the first line of the code to start running the app

**Review by ghost — COMMENTED** [review]
Integre algunos cambios y mejoras

**Review by sampolmx — COMMENTED** [review]
Thanks

**Pull request merged**
